apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: feature-store-workload
  namespace: default
  labels:
    openchoreo.dev/project: telco-fraud-detection
    openchoreo.dev/component: feature-store
spec:
  owner:
    projectName: telco-fraud-detection
    componentName: feature-store
  container:
    image: feast-serve:local
  endpoints:
    http:
      type: HTTP
      port: 6566
      visibility:
        - external
