"""adapters/ai_platform/feature_store_adapter.py — exercises the real
infra/feature-store repo (its registry.db is generated by `feast apply`, see
that directory's README)."""

import pandas as pd

from adapters.ai_platform.feature_store_adapter import FeastAdapter


def test_get_offline_features_returns_nan_for_unmatched_entity_ids() -> None:
    # No entity id matches the demo store's 1001-1010. Feast 0.66 + dask
    # 2026.7 raises on that all-NaT point-in-time join, so this exercises the
    # left-merge fallback in get_offline_features.
    adapter = FeastAdapter()

    rows = adapter.get_offline_features(["999999"], ["transaction_features:amount"])

    assert len(rows) == 1
    assert rows[0]["entity_id"] == "999999"
    assert bool(pd.isna(rows[0]["amount"]))


def test_get_offline_features_returns_values_for_matching_entity_ids() -> None:
    adapter = FeastAdapter()

    rows = adapter.get_offline_features(["1001"], ["transaction_features:amount"])

    assert rows[0]["entity_id"] == "1001"
    assert rows[0]["amount"] == 42.5


def test_list_entity_ids_returns_the_stores_ids() -> None:
    adapter = FeastAdapter()

    assert "1001" in adapter.list_entity_ids()
