apiVersion: openchoreo.dev/v1alpha1
kind: Project
metadata:
  name: telco-fraud-detection
  namespace: default
  labels:
    openchoreo.dev/name: telco-fraud-detection
  annotations:
    openchoreo.dev/display-name: Telco Fraud Detection
    openchoreo.dev/description: Telco Fraud Detection — MLOps demo (train → serve) on OpenChoreo
spec:
  type:
    kind: ClusterProjectType
    name: default
  deploymentPipelineRef:
    kind: DeploymentPipeline
    name: default
